services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:alpine3.19'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: 'randompassword'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'dbname'
    restart: always